# Generated by Django 3.2.7 on 2021-10-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=225, verbose_name='Nombre de autor')),
                ('apellidos', models.CharField(max_length=225, verbose_name='Apellido de autor')),
                ('Correo', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
            ],
        ),
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de categoria')),
                ('estado', models.BooleanField(default=True, verbose_name='Categoria Activada/Categoria Desactivada')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
